### PR TITLE
Validate contributors

### PR DESCRIPTION
**Pull request by SalmanAsh**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19)* status: all files reviewed, 2 unresolved discussions (waiting on @SalmanAsh)

___
*[`.github/actions/python/docs/action.yaml` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19#-O4lHg0YD6eHVqTJrJps:-O4lHg0YD6eHVqTJrJpt:bvt5gpo) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-backend/blob/b28af85b07c979f263d22b4b203226801018ac8b/.github/actions/python/docs/action.yaml#L1)):*
> ```YAML
> name: "Code for Life - Python - Docs"
> ```

Do we need this file in this repo?
___
*[`.github/actions/python/setup-environment/action.yaml` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19#-O4lIObD8TYXyTaOz-c9:-O4lIObD8TYXyTaOz-cA:bp6p9pn) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-backend/blob/b28af85b07c979f263d22b4b203226801018ac8b/.github/actions/python/setup-environment/action.yaml#L1)):*
> ```YAML
> name: "Code for Life - Python - Setup Environment"
> ```

Same question for this one, do we need this file in this repo?

**Review by SalmanAsh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19)* status: all files reviewed, 2 unresolved discussions (waiting on @faucomte97)

___
*[`.github/actions/python/docs/action.yaml` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19#-O4lHg0YD6eHVqTJrJps:-O4o47Xv8yqXk7h1jDp3:b-pbwk8) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-backend/blob/b28af85b07c979f263d22b4b203226801018ac8b/.github/actions/python/docs/action.yaml#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we need this file in this repo?
</blockquote></details>

Done. We don't. Deleted now.
___
*[`.github/actions/python/setup-environment/action.yaml` line 1 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19#-O4lIObD8TYXyTaOz-c9:-O4o4BlLAAXeVOre7a-y:b-pbwk8) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-backend/blob/b28af85b07c979f263d22b4b203226801018ac8b/.github/actions/python/setup-environment/action.yaml#L1)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Same question for this one, do we need this file in this repo?
</blockquote></details>

Done. We don't. Deleted now.

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @SalmanAsh)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19)* status: all files reviewed, 1 unresolved discussion (waiting on @SalmanAsh)

___
*[`.github/scripts/python/validate-existing-contributors/Pipfile` line 11 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19#-O4p9AtgCibWcWMwZnfS:-O4p9AtgCibWcWMwZnfT:bumiffu) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-backend/blob/8738aa37c441e0e40a2ecbffdf0285d91e7288ed/.github/scripts/python/validate-existing-contributors/Pipfile#L11)):*
> ```TOML
> [dev-packages]
> black = "==23.1.0"
> pytest = "==7.2.1"
> ```

I'm not sure you need `pytest here`

**Review by SalmanAsh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`.github/scripts/python/validate-existing-contributors/Pipfile` line 11 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19#-O4p9AtgCibWcWMwZnfS:-O4pCCOJCx3Q05tGhOmO:b-wnfmk9) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-backend/blob/8738aa37c441e0e40a2ecbffdf0285d91e7288ed/.github/scripts/python/validate-existing-contributors/Pipfile#L11)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

I'm not sure you need `pytest here`
</blockquote></details>

Done. Removed.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19)* status: all files reviewed, 1 unresolved discussion (waiting on @SalmanAsh)

___
*[`.github/scripts/python/validate-existing-contributors/Pipfile` line 11 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19#-O4p9AtgCibWcWMwZnfS:-O4pEhSI9QE9pJdmFVRb:bl21x5x) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-backend/blob/8738aa37c441e0e40a2ecbffdf0285d91e7288ed/.github/scripts/python/validate-existing-contributors/Pipfile#L11)):*
<details><summary><i>Previously, SalmanAsh (Salman Ashraf) wrote…</i></summary><blockquote>

Done. Removed.
</blockquote></details>

You need to re-lock after editing `Pipfile`

**Review by SalmanAsh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`.github/scripts/python/validate-existing-contributors/Pipfile` line 11 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19#-O4p9AtgCibWcWMwZnfS:-O4pXryaEF8yS6AkZPzJ:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-contributor-backend/blob/8738aa37c441e0e40a2ecbffdf0285d91e7288ed/.github/scripts/python/validate-existing-contributors/Pipfile#L11)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

You need to re-lock after editing `Pipfile`
</blockquote></details>

Done.

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-contributor-backend/19#-:-O4pYEFP8wXwoVHgCP8G:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SalmanAsh)

**Pull request merged**
